import SwiftUI
import ComposeApp

/// Bridges the shared Compose Multiplatform UI into SwiftUI. `MainViewControllerKt`
/// is generated by the Kotlin `composeApp` framework (see MainViewController.kt).
struct ComposeView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        MainViewControllerKt.MainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}

struct ContentView: View {
    var body: some View {
        ComposeView()
            .ignoresSafeArea(.keyboard)
    }
}
