// JNI bridge: wires com.v2ray.compose.vpn.V2RayBridge to Xray-core (libxray, a
// Go c-archive) and hev-socks5-tunnel (tun2socks). Built into libv2ray.so.
#include <jni.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <android/log.h>

#include "libxray.h"           // generated by xray/build-android.sh (StartXray/StopXray/XrayVersion)
#include "hev-main.h"          // from hev-socks5-tunnel

#define LOG_TAG "v2raybridge"
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN, LOG_TAG, __VA_ARGS__)

static JavaVM *g_vm = NULL;
static pthread_t g_tun_thread;
static int g_tun_fd = -1;

JNIEXPORT jint JNI_OnLoad(JavaVM *vm, void *reserved) {
    g_vm = vm;
    return JNI_VERSION_1_6;
}

// Called from Go (xray.go RegisterDialerController) to keep Xray's own sockets
// out of the VPN routing loop by calling VpnService.protect().
int protect_fd(int fd) {
    if (g_vm == NULL) return 0;
    JNIEnv *env = NULL;
    int attached = 0;
    if ((*g_vm)->GetEnv(g_vm, (void **)&env, JNI_VERSION_1_6) != JNI_OK) {
        if ((*g_vm)->AttachCurrentThread(g_vm, &env, NULL) != JNI_OK) return 0;
        attached = 1;
    }
    jclass cls = (*env)->FindClass(env, "com/v2ray/compose/vpn/V2RayVpnService");
    int ok = 0;
    if (cls != NULL) {
        jmethodID mid = (*env)->GetStaticMethodID(env, cls, "protectSocket", "(I)Z");
        if (mid != NULL) ok = (*env)->CallStaticBooleanMethod(env, cls, mid, fd) ? 1 : 0;
        (*env)->DeleteLocalRef(env, cls);
    }
    if (attached) (*g_vm)->DetachCurrentThread(g_vm);
    return ok;
}

// ---- Xray-core ----
JNIEXPORT jstring JNICALL
Java_com_v2ray_compose_vpn_V2RayBridge_startXray(JNIEnv *env, jobject thiz, jstring config) {
    const char *cfg = (*env)->GetStringUTFChars(env, config, NULL);
    char *err = StartXray((char *)cfg);
    (*env)->ReleaseStringUTFChars(env, config, cfg);
    jstring result = (*env)->NewStringUTF(env, err ? err : "");
    if (err) free(err);
    return result;
}

JNIEXPORT void JNICALL
Java_com_v2ray_compose_vpn_V2RayBridge_stopXray(JNIEnv *env, jobject thiz) {
    StopXray();
}

JNIEXPORT jstring JNICALL
Java_com_v2ray_compose_vpn_V2RayBridge_xrayVersion(JNIEnv *env, jobject thiz) {
    char *v = XrayVersion();
    jstring result = (*env)->NewStringUTF(env, v ? v : "");
    if (v) free(v);
    return result;
}

// ---- tun2socks (hev-socks5-tunnel) ----
static char g_tun_config[512];

static void *tun_thread_main(void *arg) {
    // Blocks until hev_socks5_tunnel_quit() is called.
    hev_socks5_tunnel_main_from_str((const unsigned char *)g_tun_config, strlen(g_tun_config), g_tun_fd);
    return NULL;
}

JNIEXPORT void JNICALL
Java_com_v2ray_compose_vpn_V2RayBridge_startTun2socks(JNIEnv *env, jobject thiz,
                                                      jint tunFd, jstring socksAddress,
                                                      jint socksPort, jint mtu) {
    const char *addr = (*env)->GetStringUTFChars(env, socksAddress, NULL);
    snprintf(g_tun_config, sizeof(g_tun_config),
             "tunnel:\n"
             "  mtu: %d\n"
             "socks5:\n"
             "  address: %s\n"
             "  port: %d\n"
             "  udp: 'udp'\n",
             mtu, addr, socksPort);
    (*env)->ReleaseStringUTFChars(env, socksAddress, addr);
    g_tun_fd = tunFd;
    if (pthread_create(&g_tun_thread, NULL, tun_thread_main, NULL) != 0) {
        LOGW("failed to start tun2socks thread");
    }
}

JNIEXPORT void JNICALL
Java_com_v2ray_compose_vpn_V2RayBridge_stopTun2socks(JNIEnv *env, jobject thiz) {
    hev_socks5_tunnel_quit();
    if (g_tun_fd >= 0) {
        pthread_join(g_tun_thread, NULL);
        g_tun_fd = -1;
    }
}

// ---- stats ----
// Xray exposes traffic counters only when the config carries a stats/policy/api
// block; the default generated config does not, so return zeros here. Wire the
// Xray stats API to populate these.
JNIEXPORT jlongArray JNICALL
Java_com_v2ray_compose_vpn_V2RayBridge_queryStats(JNIEnv *env, jobject thiz) {
    jlongArray arr = (*env)->NewLongArray(env, 2);
    jlong zero[2] = {0, 0};
    (*env)->SetLongArrayRegion(env, arr, 0, 2, zero);
    return arr;
}
